version: "3.8"

networks:
  network:
  ipfs-nodes:
    name: ipfs-nodes

volumes:
  sorce:
    driver: local
    driver_opts:
      type: none
      device: ../../
      # device: $PWD/${WEB_APP_PATH}
      o: bind
  ipfs-data:
  ipfs-export:
  vscode:
  home:

services:

  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      # - "--api.insecure=true"
      # - "--providers.docker"
      - "--configFile=/ctx/sorce/DeathStarGame/bin/traefik/traefik.yml"
    ports:
      # The HTTP port
      - ${PORTS_PREFIX}080:80
      - ${PORTS_PREFIX}077:7080
      # The Web UI (enabled by --api.insecure=true)
      # - "8090:8080"
    networks:
      - network
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - type: volume
        source: sorce
        target: /ctx/sorce
        volume:
          nocopy: true

  ipfs:
    # https://hub.docker.com/r/ipfs/go-ipfs/dockerfile
    image: ipfs/go-ipfs:latest
    command:
      - "daemon"
      - "--writable" 
      - "--enable-pubsub-experiment"
      - "--migrate=true"
    ports:
      - ${PORTS_PREFIX}041:4001
      - ${PORTS_PREFIX}050:5001
      - ${PORTS_PREFIX}800:8080
      - ${PORTS_PREFIX}801:8081
      # - 4001:4001
    #   - 127.0.0.1:5001:5001
    #   # - 127.0.0.1:8080:8080
    #   # - 127.0.0.1:8081:8081
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    networks:
      network:
      ipfs-nodes:
        aliases:
          - ipfs-${PORTS_PREFIX}

    volumes:
      - type: volume
        source: sorce
        target: /ctx/sorce
        volume:
          nocopy: true
      - type: volume
        source: ipfs-data
        target: /data/ipfs
        volume:
          nocopy: true
      - type: volume
        source: ipfs-export
        target: /export
        volume:
          nocopy: true

  app:
    image: deathstar.app
    build:
      context: ./app
      dockerfile: ./dev.Dockerfile
      args:
        workdir: /ctx/sorce/DeathStarGame/bin/app
    command: tail -f /dev/null
    # command: bash f dev
    # expose:
    #   - 7788
    ports:
      - ${PORTS_PREFIX}088:7788
      # - 8085:8080
    networks:
      - network
    volumes:
      - type: volume
        source: home
        target: /root
        volume:
          nocopy: true
      - type: volume
        source: sorce
        target: /ctx/sorce
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  vscode:
    image: codercom/code-server:latest
    # ports:
    #   - 8800:8080
    command: --auth none
    user: "${UID_GID}"
    environment:
       - DOCKER_USER=$USER
    networks:
      - network
    volumes:
      - type: volume
        source: sorce
        target: /ctx/sorce
        volume:
          nocopy: true
      - type: volume
        source: vscode
        target: /root
        volume:
          nocopy: true
      - type: volume
        source: ipfs-data
        target: /data/ipfs
        volume:
          nocopy: true

  # cljs-compiler:
  #   image: deathstar.cljs-compiler
  #   volumes:
  #     - ./ui/.user:/root
  #     - ./ui:/ctx/bin/ui
  #     - ../src:/ctx/src
  #   build:
  #     context: ./ui
  #     dockerfile: ./dev.Dockerfile
  #     args:
  #       workdir: /ctx/bin/ui
  #   command: tail -f /dev/null
  #   # command: bash f dev
  #   ports:
  #     - 8899:8899
  #     - 9630:9630
  #     - 9500:9500
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 4096M

  # game-ui:
  #   image: deathstar.game-ui
  #   expose:
  #     - 80
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 4096M

