version: "3.7"

networks:
  network1:
    name: ${NETWORK1}

services:

  gamehub:
    image: starnet.gamehub.prod
    build:
      context: ../
      dockerfile: ./dock/containers/gamehub/prod.Dockerfile
      args:
        dir_runner_from: dock/containers/gamehub
        dir_runner_to: /ctx/dock/containers/gamehub/
        dir_src_from: src
        dir_src_to: /ctx/src/
        cmd_build: bash f uberjar
        jar_name: app.standalone.jar
    ports:
      - 8801:8080
    networks:
      - network1
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  ui:
    image: starnet.ui.prod
    build:
      context: ../
      dockerfile: ./dock/containers/ui/prod.Dockerfile
      args:
        dir_runner_from: dock/containers/ui
        dir_runner_to: /ctx/dock/containers/ui/
        dir_src_from: src
        dir_src_to: /ctx/src/
        cmd_build: bash f release
    ports:
      - 9500:80
    stdin_open: true
    tty: true