## STATIC CONFIGURATION
# https://github.com/DoTheEvo/Traefik-v2-examples

log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: :80

# providers:
#   docker:
#     endpoint: "unix:///var/run/docker.sock"
#     exposedByDefault: false

providers:
  # Enable the file provider to define routers / middlewares / services in file
  file:
    directory: /ctx/sorce/DeathStarGame/bin/traefik/file-provider
    watch: false