entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: :8080

# providers:
#   # Enable the file provider to define routers / middlewares / services in file
#   file:
#     directory: /ctx/sorce/DeathStarGame/bin/traefik/file-provider