# http routing section
http:
  routers:
    # Define a connection between requests and services
    traefik-ui:
      service: traefik
      rule: "PathPrefix(`/traefik-ui`)"
      middlewares:
        # - "stripPrefix-traefik-ui"
        - "replacePath-traefik-ui"
    ipfs-ui:
      service: ipfs
      # rule: "PathPrefix(`/ipfs/webui`)"
      rule: "PathPrefix(`/ipfs-ui`)"
      middlewares:
        - "replacePath-ipfs-ui"
       # If the rule matches, applies the middleware
      # middlewares:
      # - test-user
      # If the rule matches, forward to the whoami service (declared below)
  
  middlewares:
    # stripPrefix-traefik-ui:
    #   stripPrefix:
    #     prefixes: 
    #     - "/traefik-ui"
    replacePath-traefik-ui:
      replacePath:
        path: "/dashboard"
    replacePath-ipfs-ui:
      replacePath:
        path: "/webui"

  # middlewares:
  #   # Define an authentication mechanism
  #   test-user:
  #     basicAuth:
  #       users:
  #       - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/

  services:
    # Define how to reach an existing service on our infrastructure
    ipfs:
      loadBalancer:
        servers:
        - url: http://ipfs:5001
    traefik:
      loadBalancer:
        servers:
        - url: http://traefik:8080