version: "3.7"

services:

  dgraph-app:
    volumes:
      - ./dgraph-app:/ctx/app
      - ./dgraph-app/.user:/root
      - ../src:/ctx/src
    build:
      context: ./dgraph-app
      dockerfile: ./Dockerfile
    # command: tail -f /dev/null
    command: bash f dev

  iam:
    volumes:
      - ./iam:/ctx/app
      - ./iam/.user:/root
      - ../src:/ctx/src
    build:
      context: ./iam
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    # command: bash f dev

  ui:
    volumes:
      - ./ui:/ctx/app
      - ../src:/ctx/src
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    # command: tail -f /dev/null
    command: bash f dev
    ports:
      - 8899:8899
      - 9500:9500
      - 9630:9630