version: "3.7"

networks:
  network1:
    name: ${NETWORK1}

services:

  dgraph-app:
    image: system.dgraph-app
    expose:
      - 8080
      - 7788
    ports:
      - 7701:7788
      - 8801:8080
    networks:
      - network1
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  iam:
    image: system.iam
    expose:
      - 8080
      - 7788
    ports:
      - 7702:7788
      - 8802:8080
    networks:
      - network1
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  ui:
    image: system.ui
    ports:
      - 9500:80
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
