version: "3.7"

networks:
  starnet.kafka-stack:
    name: starnet.kafka-stack

services:

  zookeeper:
    image: zookeeper
    build:
      context: ./zookeeper
      dockerfile: ./Dockerfile

  kafka:
    image: kafka
    build:
      context: ./kafka
      dockerfile: ./Dockerfile

  zoo1:
    image: zookeeper
    volumes:
      - ./volumes/zoo1:/opt/vol
    networks:
      - starnet.kafka-stack
    # user: user
    # ports:
    #   - 2181:2181
    # command: tail -f /dev/null
    command: bash f start
    stdin_open: true
    tty: true
    depends_on: 
      - zookeeper

  kafka1:
    image: kafka
    volumes:
      - ./volumes/kafka1:/opt/vol
    # user: user
    networks:
      - starnet.kafka-stack
    ports:
      - 9092:9092
    # command: tail -f /dev/null
    command: bash f start
    stdin_open: true
    tty: true
    depends_on: 
      - kafka
      - zoo1